### PR TITLE
Fix container

### PR DESCRIPTION
**Pull request by pabloyoyoista**
Attempt to fix the container for running tests. Likely simply running `glib-compile-schemas` after the ninja invocation could have worked, but if meson can do that directly for us, why not?

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I'm slightly confused by this change, because `ninja install` first builds the `all` alias target, then runs `meson install --no-rebuild`, while `meson install` first runs `ninja all` and then installs everything.

There should be no real difference between the two.

And neither one is going to run glib-compile-schemas for you.

On the other hand if you use https://mesonbuild.com/Gnome-module.html#gnomepost_install then *both* will run glib-compile-schemas for you.

While this is generically useful for people installing without apk and thus without package manager triggers, it still doesn't have anything to do with tests. For tests you need to compile schemas locally, not in the install tree. In that case, please use https://mesonbuild.com/Gnome-module.html#gnomecompile_schemas and add the current_build_dir to GSETTINGS_SCHEMA_DIR as part of the test setup.

**Comment by Cogitri** [comment]
The real thing which changes is that `DESTDIR` isn't set anymore, which causes the post-install script to be installed. The change from `ninja install` to `meson install` probably isn't necessary but also doesn't hurt and since we can specify more options when calling `meson install` might be an advantage in the future.

**Comment by pabloyoyoista** [comment]
> For tests you need to compile schemas locally, not in the install tree.

Could you explain the exact rationale behind this? I understand that is a common recommendation, so upstream doesn't break anything, but it is probably not so important here. I had it originally like that, but changed it because in the end what we need is a copy of the upstream schema, which we would need to keep in-sync for things we don't care about. So installing the schema globally and using it, made sense to both of us. I guess it would be different if it were our own schema that we needed for the tests.

**Comment by eli-schwartz** [comment]
> which causes the post-install script to be installed

I'd like to reiterate: what post-install script?

> Could you explain the exact rationale behind this? I understand that is a common recommendation, so upstream doesn't break anything, but it is probably not so important here.

Because `meson test` runs before `meson install`, and tests uninstalled stuff, so if you don't do *something* to set up an uninstalled environment then programs will be missing their requirements.

It's a bit odd to go install the entire project just to have the schemas installed as root, then go and test the uninstalled version of the program anyway (but rely on the installed schema alone). Not only do you become vulnerable to workflow bugs like the one currently failing the CI despite your changes, you also make it non-practical for users to test things the intuitive way.

**Comment by Cogitri** [comment]
I think you're misunderstanding the situation here, @eli-schwartz. The mentioned GSchema is the schema of a dependency (of GNOME Software), not from the plugin.

**Comment by pabloyoyoista** [comment]
I guess then what we are doing here is alright even if maybe not super orthodox.

@Cogitri I have added a new workflow to build and push container images and try to execute it so that the workflow publishes and uses user images instead of always yours. Basically to avoid you from either giving me permissions or having to push to master for the container to be published. Still, the action doesn't want to publish to my registry, I am afraid there might be some setup required. Do you have any ideas?

**Comment by Cogitri** [comment]
Hm, I didn't have to do any additional steps other than creating a token with `package:write` permissions. `GITHUB_TOKEN` that's automatically set in CI doesn't seem to cut it for some reason.

**Comment by pabloyoyoista** [comment]
So I have been looking into this with a bit more detail. I was trying to solve the problem of testing and updating the Dockerfile in pull requests. Right now only the owner of the repository can push to the registry. Therefore, changes to the Dockerfile cannot really be tested in CI by building, pushing and downloading the recently pushed container during tests. I am still a bit confused, but I understand that the reason is, that contrary to gitlab CI, pull requests run in the context of the original repository, not of the forked repository. Therefore it is harder to hand-out permissions and random users without permissions are much more restricted. So possible ideas:
 - When the Dockerfile is changed, instead of downloading the registry image build it and use it. This partially reverts to the previous behavior where the Dockerfile was always built, but only in a minority of cases. Then, the workflow on "push" events will update the image.
 - Just have a workflow on "push" events that updates the container when it changes. Then PRs that need an updated container should be split in two. First one to build the container, second one to run the tests. I'd like to avoid this if possible.
 - Give me some kind of permissions (collaborator or however it works in github), which would allow me to push to the registry on PRs. I'd say this is last resort if the others don't work.
 - Keep asking you to build and push updated images :)

I basically prefer the first option. Any opinion about it @Cogitri?

**Comment by pabloyoyoista** [comment]
Implemented version 1. The "Run tests" fail because it is still trying to pull the image. In the circumstances when the Dockerfile is updated, that workflow should be skipped, which isn't happening until this is merged because of the `pull_request_target`. Anyway, the build workflow builds the plugin and runs the tests, so that should be prove that tests are running successfully :)

**Comment by Cogitri** [comment]
Ah actually, if we only build it in a minority of cases that should be fine, let's see how master likes this

**Pull request merged**
