### PR TITLE
Upgrade to GNOME 44+ compatibility

### LINKED ISSUE #69: Changes in 44
For the record and if somebody wants to look at it:

- [ ] Add a way to show only open-source apps. We have to make sure that ours apps do not get filtered! https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1515
- [ ] The query for such apps: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1618
- [x] Preparation for async updates apps: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1615
- [x] Async updates apps: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1616
  - [x] Also port tests. Example: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1616/diffs?commit_id=3519307cf05e82430df21e0ce43a1b64b2fc15d0

This is a pretty short one, yay!

### PR DESCRIPTION
**Pull request by pabloyoyoista**
Fixes #69

### CODE REVIEW

**Comment by pabloyoyoista** [comment]
@Cogitri any idea on how to fix the pipeline issue?

dbus-daemon[99]: Failed to start message bus: Failed to bind socket "/var/run/dbus/system_bus_socket": No such file or directory

This is successfully running locally though :D

**Comment by Cogitri** [comment]
Huh, maybe that's GH actions doing some security magic?

**Comment by Cogitri** [comment]
I guess we could disable tests in the image build for now since we run them in a separate CI job as well

**Comment by pabloyoyoista** [comment]
Well, it's done like this, because the regular test job will fail until the new image uploads. And I'd bet they have the same issue. Dang :(

**Comment by pabloyoyoista** [comment]
Would you be open to merging in this state? Locally the tests are passing at least...

**Comment by pabloyoyoista** [comment]
Fix the tests! The run tests is failing due to the image not being available, but the rest is fixed! Merging!

**Pull request merged**
