### PR TITLE
Port to Software 40

### PR DESCRIPTION
**Pull request by Cogitri**

### CODE REVIEW

**Comment by pablofsf** [comment]
Since everything in this PR has been tested, would it be possible to merge it to master? Unless there is a plan to do a new release on master branch for the old 3.38 GS, is it really helpful to have this MR here? If people want to test, we could just encourage them to test master branch instead.

**Comment by Cogitri** [comment]
I’d rather have Master only contain functional changes. If this has been tested, this can be merged though, yes

**Comment by pablofsf** [comment]
I guess there it depends on what functional changes mean:

 - This branch with GS40 and GS41 builds, does not crash and shows some functionality
 - This branch with GS40 and GS41 does have some regressions compared to 0.8.2 and GS3.38. The most clear one is fixed in #15, but there might be more.

**Comment by Cogitri** [comment]
Fair enough, let’s go ahead with this :)

**Comment by pablofsf** [comment]
Great, thanks! In the following weeks I'll see if I can get some of the issues in the repo resolved, or at least finish documenting issues that I find, and then proceed to upgrade in Alpine :)

**Comment by Cogitri** [comment]
Thanks for the help on this repo :)

**Pull request merged**
